### ISSUE TITLE
Does not work well with large numbers of options

### ISSUE THREAD

**Issue by scottc-netflix** [guiyep/react-select-virtualized#62] opened 2019-11-15 00:55 UTC
Virtualization isn't nearly as performant as with react-virtualized-select. I used to be able to have 15k options no problem, but now when I click on an option it won't even register the click if there are too many options. The storybook examples with 8k+ options freeze my browser completely.

**Comment by guiyep** [comment] 2019-11-15 01:15
can you provide some examples? I don' see any issue with the storybook example at all.

**Comment by guiyep** [comment] 2019-11-15 04:33
here is an emaple with 10000 with no issue. https://codesandbox.io/s/vigilant-mclean-wpbk7

**Comment by guiyep** [comment] 2019-11-15 04:49
I will close this since it is not an issue. I show in the previous link that it works with no issue with 8000/10000 or more. If you have any problem you can use as you mention `react-virtualized-select` which is not related to this library. 

If you have more information and a replicable scenario you can create a new ticket.

Please provide a codesandbox so I can see the problem exactly and what are you doing to reproduce it.
Thanks,
Guiyep

**Closed by guiyep** 2019-11-15 04:49 UTC
Labels: kind/bug
